### ISSUE TITLE
error calling index: index of untyped nil

### ISSUE THREAD

**Issue by gour** [htkoca/theme-hugo-foundation6#16]
Hello,

I'd like to use Foundation framework for my web sites instead of (more popular Bootstrap) and here is output:
```
$ Started building sites ...
ERROR 2017/03/26 11:32:19 theme/partials/sidebar.html template: theme/partials/sidebar.html:9:27: executing "theme/partials/sidebar.html" at <index .Site.Params.s...>: error calling index: index of untyped nil
Built site for language en:
0 draft content
0 future content
0 expired content
2 regular pages created
11 other pages created
1 non-page files copied
0 paginator pages created
6 tags created
1 categories created
total in 13 ms
```

Any hint?

**Comment by htkoca** [comment]
Seems to work with the `exampleSite` content and configuration. Perhaps you're missing a `sidebar` param in your theme / site configuration? See `exampleSite/config.toml`

**Comment by gour** [comment]
> Perhaps you're missing a sidebar param in your theme / site configuration? 

You're right...forgot to uncomment it when I was playing with several themes. 😊

**Comment by htkoca** [comment]
Alright, nice getting it to work! I'm closing this issue then.
