### ISSUE TITLE
On https://themes.gohugo.io/hugo-theme-foundation6/ broken github link

### ISSUE THREAD

**Issue by rianhammer** [htkoca/theme-hugo-foundation6#18]
<a href="https://github.com/htkoca/theme-hugo-foundation6'">
https://github.com/htkoca/theme-hugo-foundation6'
</a>

There is a single quotation mark at the end of the link.

**Comment by htkoca** [comment]
Thanks, will update !

**Comment by htkoca** [comment]
This is due to gohugo.io's inability to parse "front-matter" properly. If you look at the github readme, it renders properly :). Both sites use this same readme, but display it differently.
